// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMUjc9CkAWZUxMEyI5oph_h7lppKBVYtc',
    appId: '1:155219930030:android:ad303814134298038a763f',
    messagingSenderId: '541615402790',
    projectId: 'myindiaa-dropshipping',
    storageBucket: 'myindiaa-dropshipping.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyAL1e4qMRf6EFTCYWExRvDoEq13OLtzxlE',
  //   appId: '1:541615402790:ios:9f8c21d241ed896bfb1be7',
  //   messagingSenderId: '541615402790',
  //   projectId: 'kidfluence-d5c6e',
  //   storageBucket: 'kidfluence-d5c6e.appspot.com',
  //   androidClientId: '541615402790-ca4k6n49u046ipjarna7kn5gub6i81ne.apps.googleusercontent.com',
  //   iosClientId: '541615402790-jg3cf1fdra34bjtprtu9cm2m51kocmk1.apps.googleusercontent.com',
  //   iosBundleId: 'com.techoniq.kidfluence',
  // );
}
